// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahpmfediylxclnwhzprc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocG1mZWRpeWx4Y2xud2h6cHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODQ4NTcsImV4cCI6MjA2ODU2MDg1N30.VodYw3jzWkCoD4XVT_D5fzoJpfHa2ErW2rQngb0yudc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});